Revert "Add vSphere CSI driver as tech preview"
This reverts commit 955b99e8860d0d163319edf61e07f0f4b5313c64, the image
reference is named wrong and should be vsphere-csi-driver-operator
instead.

Nightlies are currently failing:

```
error: unable to create a release: operator "cluster-storage-operator"
contained an invalid image-references file: no input image tag named
"vmware-vsphere-csi-driver-operator"
```