Revert "Install shared resource csi driver webhook alongside the shared resource csi driver"
This reverts commit 0c2757fb0652f78fa5d4c0a4fe343c659404db8c.

The commit in question has broken payload builds with the following
error:

error: failed to push image registry.ci.openshift.org/ocp/release:4.11.0-0.nightly-2022-05-16-100212: unable to upload new layer (0): Patch "https://registry.ci.openshift.org/v2/ocp/release/blobs/uploads/2b297c25-20a4-4811-b97c-bab3bafbf49d?_state=yap-S-67RRqpo0ZcQWfHZz84OreAAOIooCrJFbuNqod7Ik5hbWUiOiJvY3AvcmVsZWFzZSIsIlVVSUQiOiIyYjI5N2MyNS0yMGE0LTQ4MTEtYjk3Yy1iYWIzYmFmYmY0OWQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDUtMTZUMTA6MTA6NTAuOTc5NjQxNjkyWiJ9": operator "cluster-storage-operator" contained an invalid image-references file: no input image tag named "csi-driver-shared-resource-webhook"

See: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.11.0-0.nightly/release/4.11.0-0.nightly-2022-05-16-100212